[package]
name = "rust-fullstack-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "*"
tokio = { version = "1.29.1", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.103"